Seamly2D: VGrainlineItem Class Reference
VGrainlineItem Class Reference
#include <vgrainlineitem.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::GrainlineItem) }
Public Types inherited from VPieceItem
enum MoveType {
NotMovable = 0x0 , IsRotatable = 0x1 , IsResizable = 0x2 , IsMovable = 0x4 ,
Error = 0x8 , AllModifications = IsRotatable | IsResizable | IsMovable
}
enum { Type = UserType + static_cast<int>(Vis::PieceItem) }
Signals
void itemResized (qreal dLength)
void itemRotated (qreal dRot, const QPointF &ptNewPos)
Signals inherited from VPieceItem
void itemMoved (const QPointF &ptPos)
Public Member Functions
VGrainlineItem (QGraphicsItem *parent=nullptr)
VGrainlineItem::VGrainlineItem constructor.
virtual ~VGrainlineItem () Q_DECL_EQ_DEFAULT
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
VGrainlineItem::paint paints the item content.
void updateGeometry (const QPointF &pos, qreal rotation, qreal length, ArrowType type)
VGrainlineItem::updateGeometry updates the item with grainline parameters.
virtual int type () const Q_DECL_OVERRIDE
bool isContained (const QPointF &pt, qreal dRot, qreal &dX, qreal &dY) const
VGrainlineItem::isContained checks, if both ends of the grainline, starting at point, are contained in parent widget.
Public Member Functions inherited from VPieceItem
VPieceItem (QGraphicsItem *pParent=nullptr)
virtual ~VPieceItem ()
virtual QRectF boundingRect () const Q_DECL_OVERRIDE
boundingRect returns the item bounding box
void reset ()
reset resets the item, putting the mode and z coordinate to normal and redraws it
bool isIdle () const
isIdle returns the idle flag.
VPieceItem::MoveTypes getMoveType () const
void setMoveType (const VPieceItem::MoveTypes &moveType)
Protected Member Functions
virtual void mousePressEvent (QGraphicsSceneMouseEvent *pME) Q_DECL_OVERRIDE
VGrainlineItem::mousePressEvent handles left button mouse press events.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *pME) Q_DECL_OVERRIDE
VGrainlineItem::mouseMoveEvent handles mouse move events, making sure that the item is moved properly.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *pME) Q_DECL_OVERRIDE
VGrainlineItem::mouseReleaseEvent handles mouse release events and emits the proper signal if the item was moved.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *pME) Q_DECL_OVERRIDE
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *pME) Q_DECL_OVERRIDE
virtual void updateItem () Q_DECL_OVERRIDE
VGrainlineItem::updateItem updates the item.
void updateRectangle ()
VGrainlineItem::updateRectangle updates the polygon for the box around active item and the bounding rectangle.
virtual double GetAngle (const QPointF &pt) const Q_DECL_OVERRIDE
GetAngle calculates the angle between the line, which goes from rotation center to point and x axis.
QPointF rotate (const QPointF &pt, const QPointF &ptCenter, qreal dAng) const
VGrainlineItem::rotate rotates point around center by angle angle [rad] and returns the resulting point.
QPointF getInsideCorner (int i, qreal dDist) const
VGrainlineItem::getInsideCorner calculates a point inside the bounding polygon, distance away of i-th point in each direction.
Private Member Functions
QLineF mainLine () const
QPolygonF firstArrow () const
QPolygonF secondArrow () const
QPainterPath mainShape () const
void allUserModifications (const QPointF &pos)
void userRotateAndMove ()
void userMoveAndResize (const QPointF &pos)
void updateResizeHandle ()
Private Attributes
qreal m_rotation
qreal m_rotationStart
qreal m_length
QPolygonF m_boundingPoly
QPointF m_startPos
QPointF m_movePos
QPolygonF m_resizeHandle
qreal m_startLength
QPointF m_startPoint
QPointF m_finishPoint
QPointF m_centerPoint
qreal m_angle
ArrowType m_arrowType
qreal m_penWidth
Additional Inherited Members
Protected Types inherited from VPieceItem
enum class Mode { Normal , Move , Resize , Rotate }
Protected Attributes inherited from VPieceItem
QRectF m_boundingRect
Mode m_mode
bool m_isReleased
QPointF m_rotationCenter
VPieceItem::MoveTypes m_moveType
qreal m_inactiveZ
Detailed Description
Definition at line 58 of file vgrainlineitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 71 of file vgrainlineitem.h.
Constructor & Destructor Documentation
VGrainlineItem()
VGrainlineItem::VGrainlineItem (QGraphicsItem * parent = nullptr) explicit
VGrainlineItem::VGrainlineItem constructor.
Parameters
parent pointer to the parent item
Definition at line 79 of file vgrainlineitem.cpp.
References VPieceItem::m_inactiveZ, VPieceItem::reset(), and updateRectangle().
~VGrainlineItem()
virtual VGrainlineItem::~VGrainlineItem () virtual
Member Function Documentation
allUserModifications()
void VGrainlineItem::allUserModifications (const QPointF & pos) private
Definition at line 701 of file vgrainlineitem.cpp.
References cursorArrowCloseHand, VPieceItem::m_mode, VPieceItem::Rotate, SetItemOverrideCursor(), and userMoveAndResize().
Referenced by mousePressEvent().
firstArrow()
QPolygonF VGrainlineItem::firstArrow () const private
Definition at line 637 of file vgrainlineitem.cpp.
References ARROW_ANGLE, m_rotation, mainLine(), and qApp.
Referenced by mainShape(), and paint().
GetAngle()
double VGrainlineItem::GetAngle (const QPointF & point) const protected virtual
GetAngle calculates the angle between the line, which goes from rotation center to point and x axis.
Parameters
point point of interest
Returns
the angle between line from rotation center and point of interest and x axis
Reimplemented from VPieceItem.
Definition at line 585 of file vgrainlineitem.cpp.
References VPieceItem::GetAngle().
Referenced by mouseMoveEvent(), and mousePressEvent().
getInsideCorner()
QPointF VGrainlineItem::getInsideCorner (int i, qreal distance) const protected
VGrainlineItem::getInsideCorner calculates a point inside the bounding polygon, distance away of i-th point in each direction.
Parameters
i index of corner
distance distance
Returns
resulting point
Definition at line 615 of file vgrainlineitem.cpp.
References m_boundingPoly.
hoverEnterEvent()
void VGrainlineItem::hoverEnterEvent (QGraphicsSceneHoverEvent * pME) protected virtual
Definition at line 534 of file vgrainlineitem.cpp.
References m_penWidth.
hoverLeaveEvent()
void VGrainlineItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * pME) protected virtual
Definition at line 541 of file vgrainlineitem.cpp.
References m_penWidth.
isContained()
bool VGrainlineItem::isContained (const QPointF & point, qreal rotation, qreal & dX, qreal & dY) const
VGrainlineItem::isContained checks, if both ends of the grainline, starting at point, are contained in parent widget.
Parameters
point starting point of the grainline.
rotation rotation of the grainline in [rad]
dX horizontal translation needed to put the arrow inside parent item
dY vertical translation needed to put the arrow inside parent item
Returns
true, if both ends of the grainline, starting at point, are contained in the parent widget and false otherwise.
Definition at line 235 of file vgrainlineitem.cpp.
References m_length.
Referenced by mouseMoveEvent(), and updateGeometry().
itemResized
void VGrainlineItem::itemResized (qreal dLength) signal
Referenced by mouseReleaseEvent(), and PatternPieceTool::PatternPieceTool().
itemRotated
void VGrainlineItem::itemRotated (qreal dRot, const QPointF & ptNewPos) signal
Referenced by mouseReleaseEvent(), and PatternPieceTool::PatternPieceTool().
mainLine()
QLineF VGrainlineItem::mainLine () const private
Definition at line 629 of file vgrainlineitem.cpp.
References m_length, and m_rotation.
Referenced by firstArrow(), mainShape(), paint(), and secondArrow().
mainShape()
QPainterPath VGrainlineItem::mainShape () const private
Definition at line 665 of file vgrainlineitem.cpp.
References Bottom, firstArrow(), m_arrowType, m_penWidth, mainLine(), secondArrow(), and Top.
Referenced by shape().
mouseMoveEvent()
void VGrainlineItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
VGrainlineItem::mouseMoveEvent handles mouse move events, making sure that the item is moved properly.
Parameters
event pointer to QGraphicsSceneMouseEvent object
Definition at line 377 of file vgrainlineitem.cpp.
References GetAngle(), isContained(), VPieceItem::IsMovable, VPieceItem::IsResizable, VPieceItem::IsRotatable, m_angle, m_centerPoint, m_length, VPieceItem::m_mode, m_movePos, VPieceItem::m_moveType, m_rotation, VPieceItem::m_rotationCenter, m_rotationStart, m_startLength, m_startPos, VPieceItem::Move, qApp, VPieceItem::Resize, rotate(), VPieceItem::Rotate, updateItem(), and updateRectangle().
mousePressEvent()
void VGrainlineItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
VGrainlineItem::mousePressEvent handles left button mouse press events.
Parameters
event pointer to QGraphicsSceneMouseEvent object
Definition at line 291 of file vgrainlineitem.cpp.
References ACTIVE_Z, VPieceItem::AllModifications, allUserModifications(), cursorArrowCloseHand, GetAngle(), VPieceItem::IsMovable, VPieceItem::IsResizable, VPieceItem::IsRotatable, m_angle, m_centerPoint, m_length, VPieceItem::m_mode, m_movePos, VPieceItem::m_moveType, m_rotation, VPieceItem::m_rotationCenter, m_rotationStart, m_startLength, m_startPos, VPieceItem::Move, VPieceItem::NotMovable, VPieceItem::Rotate, SetItemOverrideCursor(), updateItem(), userMoveAndResize(), and userRotateAndMove().
mouseReleaseEvent()
void VGrainlineItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
VGrainlineItem::mouseReleaseEvent handles mouse release events and emits the proper signal if the item was moved.
Parameters
event pointer to QGraphicsSceneMouseEvent object
Definition at line 481 of file vgrainlineitem.cpp.
References cursorArrowOpenHand, VPieceItem::IsMovable, VPieceItem::IsResizable, VPieceItem::IsRotatable, VPieceItem::itemMoved(), itemResized(), itemRotated(), VPieceItem::m_isReleased, m_length, VPieceItem::m_mode, m_movePos, VPieceItem::m_moveType, m_rotation, m_startPoint, VPieceItem::Move, VPieceItem::Resize, VPieceItem::Rotate, SetItemOverrideCursor(), and updateItem().
paint()
void VGrainlineItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
VGrainlineItem::paint paints the item content.
Parameters
painter pointer to the painter object
option not used
widget not used
Definition at line 123 of file vgrainlineitem.cpp.
References Bottom, firstArrow(), m_arrowType, m_boundingPoly, m_length, VPieceItem::m_mode, m_penWidth, m_resizeHandle, m_rotation, mainLine(), Mm, VPieceItem::Normal, qApp, RECT_WIDTH, VPieceItem::Resize, VPieceItem::Rotate, ROTATE_CIRC_R, secondArrow(), Top, ToPixel(), and updateResizeHandle().
rotate()
QPointF VGrainlineItem::rotate (const QPointF & point, const QPointF & center, qreal angle) const protected
VGrainlineItem::rotate rotates point around center by angle angle [rad] and returns the resulting point.
Parameters
point point to rotate
center center of rotation
angle angle of rotation
Returns
point, which is a result of rotating point around center by angle angle
Definition at line 598 of file vgrainlineitem.cpp.
Referenced by mouseMoveEvent().
secondArrow()
QPolygonF VGrainlineItem::secondArrow () const private
Definition at line 651 of file vgrainlineitem.cpp.
References ARROW_ANGLE, m_rotation, mainLine(), and qApp.
Referenced by mainShape(), and paint().
shape()
QPainterPath VGrainlineItem::shape () const virtual
Definition at line 103 of file vgrainlineitem.cpp.
References m_boundingPoly, VPieceItem::m_mode, mainShape(), and VPieceItem::Normal.
type()
virtual int VGrainlineItem::type () const inline virtual
Reimplemented from VPieceItem.
Definition at line 70 of file vgrainlineitem.h.
References Type.
Referenced by updateGeometry().
updateGeometry()
void VGrainlineItem::updateGeometry (const QPointF & position, qreal rotation, qreal length, ArrowType type)
VGrainlineItem::updateGeometry updates the item with grainline parameters.
Parameters
position position of one grainline's end.
rotation rotation of the grainline in [degrees].
length length of the grainline in user's units.
type type of arrowhead.
Definition at line 205 of file vgrainlineitem.cpp.
References isContained(), m_arrowType, m_length, m_rotation, type(), updateItem(), and updateRectangle().
Referenced by PatternPieceTool::UpdateGrainline().
updateItem()
void VGrainlineItem::updateItem () protected virtual
VGrainlineItem::updateItem updates the item.
Implements VPieceItem.
Definition at line 550 of file vgrainlineitem.cpp.
References VPieceItem::m_boundingRect.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and updateGeometry().
updateRectangle()
void VGrainlineItem::updateRectangle () protected
VGrainlineItem::updateRectangle updates the polygon for the box around active item and the bounding rectangle.
Definition at line 559 of file vgrainlineitem.cpp.
References m_boundingPoly, VPieceItem::m_boundingRect, m_centerPoint, m_finishPoint, m_length, m_rotation, m_startPoint, RECT_WIDTH, and updateResizeHandle().
Referenced by mouseMoveEvent(), updateGeometry(), and VGrainlineItem().
updateResizeHandle()
void VGrainlineItem::updateResizeHandle () private
Definition at line 739 of file vgrainlineitem.cpp.
References m_boundingPoly, m_resizeHandle, m_rotation, and RESIZE_RECT_SIZE.
Referenced by paint(), and updateRectangle().
userMoveAndResize()
void VGrainlineItem::userMoveAndResize (const QPointF & pos) private
Definition at line 724 of file vgrainlineitem.cpp.
References cursorArrowCloseHand, VPieceItem::m_mode, m_resizeHandle, VPieceItem::Move, VPieceItem::Resize, and SetItemOverrideCursor().
Referenced by allUserModifications(), and mousePressEvent().
userRotateAndMove()
void VGrainlineItem::userRotateAndMove () private
Definition at line 714 of file vgrainlineitem.cpp.
References cursorArrowCloseHand, VPieceItem::m_mode, VPieceItem::Move, VPieceItem::Rotate, and SetItemOverrideCursor().
Referenced by mousePressEvent().
Member Data Documentation
m_angle
qreal VGrainlineItem::m_angle private
Definition at line 106 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_arrowType
ArrowType VGrainlineItem::m_arrowType private
Definition at line 107 of file vgrainlineitem.h.
Referenced by mainShape(), paint(), and updateGeometry().
m_boundingPoly
QPolygonF VGrainlineItem::m_boundingPoly private
Definition at line 98 of file vgrainlineitem.h.
Referenced by getInsideCorner(), paint(), shape(), updateRectangle(), and updateResizeHandle().
m_centerPoint
QPointF VGrainlineItem::m_centerPoint private
Definition at line 105 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and updateRectangle().
m_finishPoint
QPointF VGrainlineItem::m_finishPoint private
Definition at line 104 of file vgrainlineitem.h.
Referenced by updateRectangle().
m_length
qreal VGrainlineItem::m_length private
Definition at line 97 of file vgrainlineitem.h.
Referenced by isContained(), mainLine(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), updateGeometry(), and updateRectangle().
m_movePos
QPointF VGrainlineItem::m_movePos private
Definition at line 100 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_penWidth
qreal VGrainlineItem::m_penWidth private
Definition at line 108 of file vgrainlineitem.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), mainShape(), and paint().
m_resizeHandle
QPolygonF VGrainlineItem::m_resizeHandle private
Definition at line 101 of file vgrainlineitem.h.
Referenced by paint(), updateResizeHandle(), and userMoveAndResize().
m_rotation
qreal VGrainlineItem::m_rotation private
Definition at line 95 of file vgrainlineitem.h.
Referenced by firstArrow(), mainLine(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), secondArrow(), updateGeometry(), updateRectangle(), and updateResizeHandle().
m_rotationStart
qreal VGrainlineItem::m_rotationStart private
Definition at line 96 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_startLength
qreal VGrainlineItem::m_startLength private
Definition at line 102 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_startPoint
QPointF VGrainlineItem::m_startPoint private
Definition at line 103 of file vgrainlineitem.h.
Referenced by mouseReleaseEvent(), and updateRectangle().
m_startPos
QPointF VGrainlineItem::m_startPos private
Definition at line 99 of file vgrainlineitem.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
src/libs/vwidgets/vgrainlineitem.h
src/libs/vwidgets/vgrainlineitem.cpp