Seamly2D: VLayoutPaper Class Reference
VLayoutPaper Class Reference
#include <vlayoutpaper.h>
Public Member Functions
VLayoutPaper ()
VLayoutPaper (int height, int width)
VLayoutPaper (const VLayoutPaper &paper)
~VLayoutPaper ()
Destroys this VLayoutPaper.
VLayoutPaper & operator= (const VLayoutPaper &paper)
Assigns paper to this paper and returns a reference to this.
void Swap (VLayoutPaper &paper) Q_DECL_NOTHROW
int GetHeight () const
GetHeight gets the height of the paper.
void setHeight (int height)
setHeight sets the height of the paper.
int GetWidth () const
GetHeight sets the height of the paper.
void SetWidth (int width)
setHeight sets the width of the paper.
qreal getLayoutGap () const
getLayoutGap gets the gap width of the layout.
void setLayoutGap (qreal width)
setLayoutGap sets the gap width of the layout.
quint32 GetShift () const
GetShift gets the shift of the paper.
void SetShift (quint32 shift)
SetShift sets the shift of the paper.
bool GetRotate () const
GetRotate gets the paper rotation.
void SetRotate (bool value)
SetRotate sets the paper is rotated.
int GetRotationIncrease () const
GetRotationIncrease gets the rotation increment.
void SetRotationIncrease (int value)
SetRotationIncrease sets the rotation increment.
bool IsSaveLength () const
IsSaveLength gets savelength of the layout.
void SetSaveLength (bool value)
SetSaveLength sets savelength of the layout.
void setPaperIndex (quint32 index)
setPaperIndex sets the paper index.
bool arrangePiece (const VLayoutPiece &piece, std::atomic_bool &stop)
int Count () const
Count returns the number of piece.
Q_REQUIRED_RESULT QGraphicsRectItem * getPaperItem (bool autoCrop, bool textAsPaths) const
getPaperItem returns paper an item.
Q_REQUIRED_RESULT QList< QGraphicsItem * > getPieceItems (bool textAsPaths) const
getPieceItems returns the piece items in the layout.
QVector< VLayoutPiece > getPieces () const
getPieces returns the pieces in the layout.
void setPieces (const QList< VLayoutPiece > &pieces)
setPieces sets the pieces in the layout.
QRectF piecesBoundingRect () const
piecesBoundingRect returns the bounding rect of pieces.
Private Member Functions
bool addToSheet (const VLayoutPiece &piece, std::atomic_bool &stop)
addToSheet add piece to layout page.
bool saveResult (const VBestSquare &bestResult, const VLayoutPiece &piece)
Private Attributes
QSharedDataPointer< VLayoutPaperData > d
Detailed Description
Definition at line 72 of file vlayoutpaper.h.
Constructor & Destructor Documentation
VLayoutPaper() [1/3]
VLayoutPaper::VLayoutPaper ()
Definition at line 87 of file vlayoutpaper.cpp.
VLayoutPaper() [2/3]
VLayoutPaper::VLayoutPaper (int height, int width)
Definition at line 92 of file vlayoutpaper.cpp.
VLayoutPaper() [3/3]
VLayoutPaper::VLayoutPaper (const VLayoutPaper & paper)
Definition at line 97 of file vlayoutpaper.cpp.
~VLayoutPaper()
VLayoutPaper::~VLayoutPaper ()
Destroys this VLayoutPaper.
Definition at line 117 of file vlayoutpaper.cpp.
Member Function Documentation
addToSheet()
bool VLayoutPaper::addToSheet (const VLayoutPiece & piece, std::atomic_bool & stop) private
addToSheet add piece to layout page.
This method adds a piece to a layout page.
Parameters
piece piece being added to page.
stop shared bool between threads.
Returns
bool true if valid result, false if invalid result.
Definition at line 378 of file vlayoutpaper.cpp.
References d, VLayoutPiece::LayoutEdgesCount(), VBestSquare::NewResult(), VLayoutPiece::pieceEdgesCount(), and saveResult().
Referenced by arrangePiece().
arrangePiece()
bool VLayoutPaper::arrangePiece (const VLayoutPiece & piece, std::atomic_bool & stop)
Definition at line 330 of file vlayoutpaper.cpp.
References addToSheet(), d, VAbstractPiece::IsForbidFlipping(), VLayoutPiece::LayoutEdgesCount(), and VLayoutPiece::pieceEdgesCount().
Referenced by VLayoutGenerator::Generate().
Count()
int VLayoutPaper::Count () const
Count returns the number of piece.
This method returns number of pieces used in the layout.
Returns
int count.
Definition at line 364 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::Generate().
GetHeight()
int VLayoutPaper::GetHeight () const
GetHeight gets the height of the paper.
This method gets the height of the paper.
Returns
int height of paper.
Definition at line 127 of file vlayoutpaper.cpp.
References d.
getLayoutGap()
qreal VLayoutPaper::getLayoutGap () const
getLayoutGap gets the gap width of the layout.
This method gets the ga width of the layout.
Returns
qreal width of gap.
Definition at line 177 of file vlayoutpaper.cpp.
References d.
getPaperItem()
QGraphicsRectItem * VLayoutPaper::getPaperItem (bool autoCrop, bool textAsPaths) const
getPaperItem returns paper an item.
This method returns a paper (page) as a QGraphicsRectItem.
Parameters
autoCrop If true autocrop the page, if false otherwise.
textAsPaths If true append text as a path, if false otherwise.
Returns
paper.
Definition at line 466 of file vlayoutpaper.cpp.
References d, and getPieceItems().
getPieceItems()
QList< QGraphicsItem * > VLayoutPaper::getPieceItems (bool textAsPaths) const
getPieceItems returns the piece items in the layout.
This method returns list of pieces used in the layout as graphicitems.
Parameters
textAsPaths if true append text as path, if false otherwise.
Returns
QList<QGraphicsItem.
Definition at line 504 of file vlayoutpaper.cpp.
References d.
Referenced by getPaperItem().
getPieces()
QVector< VLayoutPiece > VLayoutPaper::getPieces () const
getPieces returns the pieces in the layout.
This method returns a vector of pieces used in the layout.
Returns
QVector<VLayoutPiece>.
Definition at line 521 of file vlayoutpaper.cpp.
References d.
GetRotate()
bool VLayoutPaper::GetRotate () const
GetRotate gets the paper rotation.
This method gets whether the paper is rotated i.e. it's orientation.
Returns
bool.
true paper is rotated. (landscape)
false paper is not rotated. (portrait)
Definition at line 232 of file vlayoutpaper.cpp.
References d.
GetRotationIncrease()
int VLayoutPaper::GetRotationIncrease () const
GetRotationIncrease gets the rotation increment.
This method gets the rotation increment.
Returns
int rotation increment.
Definition at line 260 of file vlayoutpaper.cpp.
References d.
GetShift()
quint32 VLayoutPaper::GetShift () const
GetShift gets the shift of the paper.
This method gets the shift length of the paper as set in the layout settings dialog.
Returns
quint32 shift length.
Definition at line 205 of file vlayoutpaper.cpp.
References d.
GetWidth()
int VLayoutPaper::GetWidth () const
GetHeight sets the height of the paper.
This method sets the height of the paper.
Returns
int height of paper.
Definition at line 152 of file vlayoutpaper.cpp.
References d.
IsSaveLength()
bool VLayoutPaper::IsSaveLength () const
IsSaveLength gets savelength of the layout.
This method gets whether to save the length of the layout.
Returns
bool.
true save length.
false don't save length.
Definition at line 296 of file vlayoutpaper.cpp.
References d.
operator=()
VLayoutPaper & VLayoutPaper::operator= (const VLayoutPaper & paper)
Assigns paper to this paper and returns a reference to this.
Definition at line 104 of file vlayoutpaper.cpp.
References d.
piecesBoundingRect()
QRectF VLayoutPaper::piecesBoundingRect () const
piecesBoundingRect returns the bounding rect of pieces.
This method returns bounding rect of all the pieces used in the layout.
Returns
QRectF bounding rect of pieces.
Definition at line 546 of file vlayoutpaper.cpp.
References d.
saveResult()
bool VLayoutPaper::saveResult (const VBestSquare & bestResult, const VLayoutPiece & piece) private
Definition at line 436 of file vlayoutpaper.cpp.
References d, VBestSquare::GContourEdge(), VBestSquare::isMirror(), VBestSquare::pieceEdge(), VLayoutPiece::SetMirror(), VLayoutPiece::setTransform(), VBestSquare::Transform(), VBestSquare::Type(), and VBestSquare::ValidResult().
Referenced by addToSheet().
setHeight()
void VLayoutPaper::setHeight (int height)
setHeight sets the height of the paper.
This method sets the height of the paper.
Parameters
height of paper.
Returns
void.
Definition at line 140 of file vlayoutpaper.cpp.
References d.
setLayoutGap()
void VLayoutPaper::setLayoutGap (qreal width)
setLayoutGap sets the gap width of the layout.
This method sets the gap width of the layout.
Parameters
width of gap.
Returns
void.
Definition at line 190 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
setPaperIndex()
void VLayoutPaper::setPaperIndex (quint32 index)
setPaperIndex sets the paper index.
This method sets the paper index.
Parameters
index paper index.
Returns
void.
Definition at line 324 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
setPieces()
void VLayoutPaper::setPieces (const QList< VLayoutPiece > & pieces)
setPieces sets the pieces in the layout.
This method converts and sets a vector from list of pieces used in the layout.
Parameters
pieces list of layout pieces.
Returns
void.
Definition at line 534 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), and VLayoutGenerator::unitePages().
SetRotate()
void VLayoutPaper::SetRotate (bool value)
SetRotate sets the paper is rotated.
This method sets whether the paper is rotated i.e. the orientation.
Parameters
value
true paper is rotated. (landscape)
false paper is not rotated. (portrait)
Returns
void.
Definition at line 247 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
SetRotationIncrease()
void VLayoutPaper::SetRotationIncrease (int value)
SetRotationIncrease sets the rotation increment.
This method sets the rotation increment.
Parameters
value rotation increment.
Returns
void.
Definition at line 273 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
SetSaveLength()
void VLayoutPaper::SetSaveLength (bool value)
SetSaveLength sets savelength of the layout.
This method sets whether to save the length of the layout.
Parameters
value.
true save length.
false don't save length.
Returns
void.
Definition at line 311 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
SetShift()
void VLayoutPaper::SetShift (quint32 shift)
SetShift sets the shift of the paper.
This method sets the shift of the paper.
Parameters
shift of the paper.
Returns
void.
Definition at line 218 of file vlayoutpaper.cpp.
References d.
Referenced by VLayoutGenerator::gatherPages(), VLayoutGenerator::Generate(), and VLayoutGenerator::unitePages().
SetWidth()
void VLayoutPaper::SetWidth (int width)
setHeight sets the width of the paper.
This method sets the width of the paper.
Parameters
width of paper.
Returns
void.
Definition at line 165 of file vlayoutpaper.cpp.
References d.
Swap()
void VLayoutPaper::Swap (VLayoutPaper & paper)
Definition at line 83 of file vlayoutpaper.cpp.
Member Data Documentation
d
QSharedDataPointer<VLayoutPaperData> VLayoutPaper::d private
Definition at line 124 of file vlayoutpaper.h.
Referenced by addToSheet(), arrangePiece(), Count(), GetHeight(), getLayoutGap(), getPaperItem(), getPieceItems(), getPieces(), GetRotate(), GetRotationIncrease(), GetShift(), GetWidth(), IsSaveLength(), operator=(), piecesBoundingRect(), saveResult(), setHeight(), setLayoutGap(), setPaperIndex(), setPieces(), SetRotate(), SetRotationIncrease(), SetSaveLength(), SetShift(), and SetWidth().
The documentation for this class was generated from the following files:
src/libs/vlayout/vlayoutpaper.h
src/libs/vlayout/vlayoutpaper.cpp