Seamly2D: VLayoutGenerator Class Reference
VLayoutGenerator Class Reference
#include <vlayoutgenerator.h>
Public Slots
void Abort ()
Abort abort layout generation.
Signals
void Start ()
void Arranged (int count)
void Error (const LayoutErrors &state)
void Finished ()
Public Member Functions
VLayoutGenerator (QObject *parent=nullptr)
virtual ~VLayoutGenerator () Q_DECL_OVERRIDE
Destroys this VLayoutGenerator.
void setPieces (const QVector< VLayoutPiece > &details)
setPieces sets the bank pieces.
void setLayoutGap (qreal width)
setLayoutGap sets layout gap width.
void setCaseType (Cases caseType)
setCaseType sets the case type.
int PieceCount ()
qreal GetPaperHeight () const
GetPaperHeight gets the paper height.
void SetPaperHeight (qreal value)
SetPaperHeight sets layout height.
qreal GetPaperWidth () const
GetPaperWidth gets the paper width.
void SetPaperWidth (qreal value)
SetPaperWidth sets layout width.
bool IsUsePrinterFields () const
IsUsePrinterFields gets whether to use the margins.
QMarginsF GetPrinterFields () const
GetPrinterFields gets the margins.
void SetPrinterFields (bool usePrinterFields, const QMarginsF &value)
SetPrinterFields sets the paper marguins.
quint32 GetShift () const
GetShift gets the shift.
void SetShift (quint32 shift)
SetShift sets the shift.
void Generate ()
Generate generate layout.
LayoutErrors State () const
State gets the error state.
Q_REQUIRED_RESULT QList< QGraphicsItem * > GetPapersItems () const
GetPapersItems gets a list of paper items.
Q_REQUIRED_RESULT QList< QList< QGraphicsItem * > > getAllPieceItems () const
getAllPieceItems gets a list of all piece items.
QVector< QVector< VLayoutPiece > > getAllPieces () const
getAllPieces gets a list of all pieces.
bool GetRotate () const
GetRotate gets whether the paper should rotate.
void SetRotate (bool value)
SetRotate sets whether the paper should rotate.
int GetRotationIncrease () const
void SetRotationIncrease (int value)
SetRotationIncrease sets sets the rotation increment.
bool GetAutoCrop () const
GetAutoCrop gets the paper width.
void SetAutoCrop (bool value)
SetAutoCrop sets whether to crop paper.
bool IsSaveLength () const
void SetSaveLength (bool value)
bool IsUnitePages () const
IsUnitePages gets whether to unite pages.
void SetUnitePages (bool value)
SetUnitePages sets whether to unite pages.
quint8 GetMultiplier () const
GetMultiplier gets the multipler.
void SetMultiplier (const quint8 &value)
SetMultiplier sets the multipler.
bool useStripOptimization () const
useStripOptimization gets whether to use strip optimization.
void setStripOptimization (bool value)
setStripOptimization sets whether to use strip optimization.
bool isTextAsPaths () const
isTextAsPaths gets whether to render text as path.
void setTextAsPaths (bool value)
setTextAsPaths sets whether to render text as path.
Private Member Functions
int pageHeight () const
pageHeight gets the page height.
int pageWidth () const
pageWidth gets the page width.
void gatherPages ()
gatherPages Unite layout pages with optimization.
void unitePages ()
unitePages Unite layout pages.
void unitePieces (int j, QList< QList< VLayoutPiece > > &pieces, qreal length, int i)
unitePieces combines layout pieces.
void unitePapers (int j, QList< qreal > &papersLength, qreal length)
unitePapers combines page lengths into one.
QList< VLayoutPiece > movePieces (qreal length, const QVector< VLayoutPiece > &pieces)
movePieces move pieces.
Private Attributes
QVector< VLayoutPaper > m_papers
VBank * m_bank
qreal m_paperHeight
qreal m_paperWidth
QMarginsF m_margins
bool m_usePrinterFields
std::atomic_bool m_stopGeneration
LayoutErrors m_state
quint32 m_shift
bool m_rotate
int m_rotationIncrement
bool m_autoCrop
bool m_saveLength
bool m_unitePages
bool m_stripOptimized
quint8 m_multiplier
bool m_useStripOptimization
bool m_textAsPaths
Detailed Description
Definition at line 73 of file vlayoutgenerator.h.
Constructor & Destructor Documentation
VLayoutGenerator()
VLayoutGenerator::VLayoutGenerator (QObject * parent = nullptr) explicit
Definition at line 64 of file vlayoutgenerator.cpp.
~VLayoutGenerator()
VLayoutGenerator::~VLayoutGenerator () virtual
Destroys this VLayoutGenerator.
Definition at line 89 of file vlayoutgenerator.cpp.
References m_bank.
Member Function Documentation
Abort
void VLayoutGenerator::Abort () slot
Abort abort layout generation.
This method aborts the layout generation.
Returns
void
Definition at line 321 of file vlayoutgenerator.cpp.
References m_state, m_stopGeneration, and ProcessStoped.
Referenced by MainWindowsNoGUI::LayoutSettings().
Arranged
void VLayoutGenerator::Arranged (int count) signal
Referenced by Generate(), and MainWindowsNoGUI::LayoutSettings().
Error
void VLayoutGenerator::Error (const LayoutErrors & state) signal
Referenced by Generate(), and MainWindowsNoGUI::LayoutSettings().
Finished
void VLayoutGenerator::Finished () signal
Referenced by Generate(), and MainWindowsNoGUI::LayoutSettings().
gatherPages()
void VLayoutGenerator::gatherPages () private
gatherPages Unite layout pages with optimization.
This method unites the layout pages if there is more than 1 page with strip optimization.
Returns
void.
Definition at line 449 of file vlayoutgenerator.cpp.
References VBank::getLayoutGap(), m_bank, m_paperHeight, m_papers, m_rotate, m_rotationIncrement, m_saveLength, m_shift, pageHeight(), pageWidth(), VLayoutPaper::setLayoutGap(), VLayoutPaper::setPaperIndex(), VLayoutPaper::setPieces(), VLayoutPaper::SetRotate(), VLayoutPaper::SetRotationIncrease(), VLayoutPaper::SetSaveLength(), VLayoutPaper::SetShift(), and unitePieces().
Referenced by Generate().
Generate()
void VLayoutGenerator::Generate ()
Generate generate layout.
This method generates the pattern layout.
Returns
void.
Definition at line 150 of file vlayoutgenerator.cpp.
References VBank::allPieceCount(), Arranged(), VBank::Arranged(), VBank::ArrangedCount(), VLayoutPaper::arrangePiece(), VLayoutPaper::Count(), EmptyPaperError, Error(), Finished(), gatherPages(), VBank::GetBiggestDiagonal(), VBank::getLayoutGap(), VBank::getPiece(), VBank::GetTiket(), IsUnitePages(), VBank::LeftArrange(), m_bank, m_multiplier, m_papers, m_rotate, m_rotationIncrement, m_saveLength, m_shift, m_state, m_stopGeneration, m_stripOptimized, m_useStripOptimization, NoError, VBank::NotArranged(), pageHeight(), pageWidth(), VBank::Prepare(), PrepareLayoutError, VLayoutPaper::setLayoutGap(), VLayoutPaper::setPaperIndex(), VLayoutPaper::SetRotate(), VLayoutPaper::SetRotationIncrease(), VLayoutPaper::SetSaveLength(), VLayoutPaper::SetShift(), Start(), and unitePages().
Referenced by MainWindowsNoGUI::LayoutSettings().
getAllPieceItems()
QList< QList< QGraphicsItem * > > VLayoutGenerator::getAllPieceItems () const
getAllPieceItems gets a list of all piece items.
This method get all the piece item on the layout papers (pages).
@Details If the item is a text item and isTextAsPaths is true, text item is convetd to a path.
Returns
list QGraphicsItem of layout pieces.
Definition at line 287 of file vlayoutgenerator.cpp.
References isTextAsPaths(), and m_papers.
Referenced by MainWindowsNoGUI::LayoutSettings().
getAllPieces()
QVector< QVector< VLayoutPiece > > VLayoutGenerator::getAllPieces () const
getAllPieces gets a list of all pieces.
This method get all the pieces on the layout papers (pages).
Returns
list Qvector of layout pieces.
Definition at line 304 of file vlayoutgenerator.cpp.
References m_papers.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetAutoCrop()
bool VLayoutGenerator::GetAutoCrop () const
GetAutoCrop gets the paper width.
This method gets whether to crop the unused portion of paper.
Returns
true if the paper should be cropped, false otherwise.
Definition at line 688 of file vlayoutgenerator.cpp.
References m_autoCrop.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetMultiplier()
quint8 VLayoutGenerator::GetMultiplier () const
GetMultiplier gets the multipler.
This method gets thew multipler used in the strip optimization.
Returns
m_multiplier.
Definition at line 387 of file vlayoutgenerator.cpp.
References m_multiplier.
GetPaperHeight()
qreal VLayoutGenerator::GetPaperHeight () const
GetPaperHeight gets the paper height.
This method gets the height of the paper.
Returns
qreal paper height.
Definition at line 848 of file vlayoutgenerator.cpp.
References m_paperHeight.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetPapersItems()
QList< QGraphicsItem * > VLayoutGenerator::GetPapersItems () const
GetPapersItems gets a list of paper items.
This method converts a vector of layout papers (pages) and returns a list of QGraphicItems.
Returns
list.
Definition at line 267 of file vlayoutgenerator.cpp.
References isTextAsPaths(), m_autoCrop, and m_papers.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetPaperWidth()
qreal VLayoutGenerator::GetPaperWidth () const
GetPaperWidth gets the paper width.
This method gets the width of the paper.
Returns
qreal paper width.
Definition at line 760 of file vlayoutgenerator.cpp.
References m_paperWidth.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetPrinterFields()
QMarginsF VLayoutGenerator::GetPrinterFields () const
GetPrinterFields gets the margins.
This method gets the paper margins set in the layout dialog.
Returns
margins.
Definition at line 796 of file vlayoutgenerator.cpp.
References m_margins.
Referenced by MainWindowsNoGUI::LayoutSettings().
GetRotate()
bool VLayoutGenerator::GetRotate () const
GetRotate gets whether the paper should rotate.
This method gets whether to rotate the paper.
Returns
true if the paper should be rotated, false otherwise.
Definition at line 736 of file vlayoutgenerator.cpp.
References m_rotate.
GetRotationIncrease()
int VLayoutGenerator::GetRotationIncrease () const
Definition at line 707 of file vlayoutgenerator.cpp.
References m_rotationIncrement.
GetShift()
quint32 VLayoutGenerator::GetShift () const
GetShift gets the shift.
This method gets the shift offset length that is set in the layout dialog.
Returns
shift.
Definition at line 823 of file vlayoutgenerator.cpp.
References m_shift.
IsSaveLength()
bool VLayoutGenerator::IsSaveLength () const
Definition at line 669 of file vlayoutgenerator.cpp.
References m_saveLength.
isTextAsPaths()
bool VLayoutGenerator::isTextAsPaths () const
isTextAsPaths gets whether to render text as path.
This method gets whether text is rendered as a path.
Returns
m_unitePages true if text should be rendered as a path false if otherwise.
Definition at line 363 of file vlayoutgenerator.cpp.
References m_textAsPaths.
Referenced by getAllPieceItems(), and GetPapersItems().
IsUnitePages()
bool VLayoutGenerator::IsUnitePages () const
IsUnitePages gets whether to unite pages.
This method gets whether the pages (if possible) should e united into 1 page.
Returns
m_unitePages true if pages should be united false if otherwise.
Definition at line 651 of file vlayoutgenerator.cpp.
References m_unitePages.
Referenced by Generate(), and MainWindowsNoGUI::LayoutSettings().
IsUsePrinterFields()
bool VLayoutGenerator::IsUsePrinterFields () const
IsUsePrinterFields gets whether to use the margins.
This method gets whether to use the paper margins set in the layout dialog.
Returns
true if the layout paper should use the margins, false otherwise.
Definition at line 784 of file vlayoutgenerator.cpp.
References m_usePrinterFields.
Referenced by MainWindowsNoGUI::LayoutSettings().
movePieces()
QList< VLayoutPiece > VLayoutGenerator::movePieces (qreal length, const QVector< VLayoutPiece > & pieces) private
movePieces move pieces.
This method combines the layout pieces into one list .
Parameters
length of page.
pieces vector of all the layout pieces.
Returns
newPieces. Combined list of layout pieces from all the pages.
Definition at line 626 of file vlayoutgenerator.cpp.
References VLayoutPiece::Translate().
Referenced by unitePieces().
pageHeight()
int VLayoutGenerator::pageHeight () const private
pageHeight gets the page height.
This method gets the height of the page which equals the paper height minus the top and bottom margins.
Returns
int page height.
Definition at line 424 of file vlayoutgenerator.cpp.
References m_margins, and m_paperHeight.
Referenced by gatherPages(), and Generate().
pageWidth()
int VLayoutGenerator::pageWidth () const private
pageWidth gets the page width.
This method gets the width of the page which equals the paper width minus the left and right margins.
Returns
int paper width.
Definition at line 437 of file vlayoutgenerator.cpp.
References m_margins, and m_paperWidth.
Referenced by gatherPages(), Generate(), and unitePages().
PieceCount()
int VLayoutGenerator::PieceCount ()
Definition at line 139 of file vlayoutgenerator.cpp.
References VBank::allPieceCount(), and m_bank.
SetAutoCrop()
void VLayoutGenerator::SetAutoCrop (bool value)
SetAutoCrop sets whether to crop paper.
This method sets whether to crop the unused portion of paper.
Parameters
value true if the paper should be cropped, false otherwise.
Definition at line 700 of file vlayoutgenerator.cpp.
References m_autoCrop.
Referenced by LayoutSettingsDialog::DialogAccepted().
setCaseType()
void VLayoutGenerator::setCaseType (Cases caseType)
setCaseType sets the case type.
This method sets the case type for choosing the next workpiece as set in the layout settings dialog.
Parameters
caseType
Three groups: big, middle, small.
Two groups: big, small.
Descending area.
Returns
void
Definition at line 132 of file vlayoutgenerator.cpp.
References m_bank, and VBank::setCaseType().
Referenced by LayoutSettingsDialog::DialogAccepted().
setLayoutGap()
void VLayoutGenerator::setLayoutGap (qreal width)
setLayoutGap sets layout gap width.
This method sets the width of the gap layout.
Parameters
width width of gap.
Returns
void.
Definition at line 115 of file vlayoutgenerator.cpp.
References m_bank, and VBank::setLayoutGap().
Referenced by LayoutSettingsDialog::DialogAccepted().
SetMultiplier()
void VLayoutGenerator::SetMultiplier (const quint8 & value)
SetMultiplier sets the multipler.
This method sets the multipler used in the strip optimization from the layout setting dialog.
Parameters
value from 1 to 10.
Returns
void.
Definition at line 400 of file vlayoutgenerator.cpp.
References m_multiplier.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetPaperHeight()
void VLayoutGenerator::SetPaperHeight (qreal value)
SetPaperHeight sets layout height.
This method sets the height of the paper.
Parameters
value height of paper.
Definition at line 860 of file vlayoutgenerator.cpp.
References m_paperHeight.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetPaperWidth()
void VLayoutGenerator::SetPaperWidth (qreal value)
SetPaperWidth sets layout width.
This method sets the width of the paper.
Parameters
value width of paper.
Definition at line 772 of file vlayoutgenerator.cpp.
References m_paperWidth.
Referenced by LayoutSettingsDialog::DialogAccepted().
setPieces()
void VLayoutGenerator::setPieces (const QVector< VLayoutPiece > & pieces)
setPieces sets the bank pieces.
This method sets the bank to the vector of layout pieces.
Parameters
pieces vector of layout pieces.
Returns
void.
Definition at line 102 of file vlayoutgenerator.cpp.
References m_bank, and VBank::setPieces().
Referenced by MainWindowsNoGUI::LayoutSettings().
SetPrinterFields()
void VLayoutGenerator::SetPrinterFields (bool usePrinterFields, const QMarginsF & value)
SetPrinterFields sets the paper marguins.
This method sets whether to use the paper margins. Also sets the paper margins set in the layout dialog.
Parameters
value paper margins.
usePrinterFields true if the layout paper should use the margins, false otherwise.
Definition at line 810 of file vlayoutgenerator.cpp.
References m_margins, and m_usePrinterFields.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetRotate()
void VLayoutGenerator::SetRotate (bool value)
SetRotate sets whether the paper should rotate.
This method sets whether to rotate the paper.
Parameters
value true if the paper should be rotated, false otherwise.
Definition at line 748 of file vlayoutgenerator.cpp.
References m_rotate.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetRotationIncrease()
void VLayoutGenerator::SetRotationIncrease (int value)
SetRotationIncrease sets sets the rotation increment.
This method sets rotation increment of the paper.
Parameters
value rotation increment.
Definition at line 719 of file vlayoutgenerator.cpp.
References m_rotationIncrement.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetSaveLength()
void VLayoutGenerator::SetSaveLength (bool value)
Definition at line 676 of file vlayoutgenerator.cpp.
References m_saveLength.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetShift()
void VLayoutGenerator::SetShift (quint32 shift)
SetShift sets the shift.
This method sets the shift offset length that is set in the layout dialog.
Parameters
shift
Returns
void.
Definition at line 836 of file vlayoutgenerator.cpp.
References m_shift.
Referenced by LayoutSettingsDialog::DialogAccepted().
setStripOptimization()
void VLayoutGenerator::setStripOptimization (bool value)
setStripOptimization sets whether to use strip optimization.
This method sets whether to use strip optimization when uniting pages.
Parameters
bool value
true if optimization should be used when uniting pages.
false if otherwise.
Definition at line 351 of file vlayoutgenerator.cpp.
References m_useStripOptimization.
Referenced by LayoutSettingsDialog::DialogAccepted().
setTextAsPaths()
void VLayoutGenerator::setTextAsPaths (bool value)
setTextAsPaths sets whether to render text as path.
This method gets whether text is rendered as a path.
Returns
m_unitePages true if text should be rendered as a path false if otherwise.
Definition at line 375 of file vlayoutgenerator.cpp.
References m_textAsPaths.
Referenced by LayoutSettingsDialog::DialogAccepted().
SetUnitePages()
void VLayoutGenerator::SetUnitePages (bool value)
SetUnitePages sets whether to unite pages.
This method sets whether the pages (if possible) should e united into 1 page..
Returns
m_unitePages true if pages should be united false if otherwise.
Definition at line 663 of file vlayoutgenerator.cpp.
References m_unitePages.
Referenced by LayoutSettingsDialog::DialogAccepted().
Start
void VLayoutGenerator::Start () signal
Referenced by Generate(), and MainWindowsNoGUI::LayoutSettings().
State()
LayoutErrors VLayoutGenerator::State () const
State gets the error state.
This method returns any layout generator errors.
Returns
m_state Could be one one the following:
NoError
PrepareLayoutError
ProcessStoped
EmptyPaperError
Definition at line 255 of file vlayoutgenerator.cpp.
References m_state.
Referenced by MainWindowsNoGUI::LayoutSettings().
unitePages()
void VLayoutGenerator::unitePages () private
unitePages Unite layout pages.
This method unites the layout pages if there is more than 1 page. It first crops any page if the autocrop is true, and then appends them 1 at a time into 1 page.
Returns
void.
Definition at line 510 of file vlayoutgenerator.cpp.
References VBank::getLayoutGap(), m_autoCrop, m_bank, m_papers, m_rotate, m_rotationIncrement, m_saveLength, m_shift, pageWidth(), QIMAGE_MAX, VLayoutPaper::setLayoutGap(), VLayoutPaper::setPaperIndex(), VLayoutPaper::setPieces(), VLayoutPaper::SetRotate(), VLayoutPaper::SetRotationIncrease(), VLayoutPaper::SetSaveLength(), VLayoutPaper::SetShift(), unitePapers(), and unitePieces().
Referenced by Generate().
unitePapers()
void VLayoutGenerator::unitePapers (int j, QList< qreal > & papersLength, qreal length) private
unitePapers combines page lengths into one.
This method combines the page lengths into one list .
Parameters
papersLength list of page lengths.
length length of page.
Returns
void.
Definition at line 605 of file vlayoutgenerator.cpp.
Referenced by unitePages().
unitePieces()
void VLayoutGenerator::unitePieces (int j, QList< QList< VLayoutPiece > > & pieces, qreal length, int i) private
unitePieces combines layout pieces.
This method combines the layout pieces into one list .
Parameters
pieces list of layout pieces.
length length of page.
i number of page.
Returns
void.
Definition at line 584 of file vlayoutgenerator.cpp.
References m_papers, and movePieces().
Referenced by gatherPages(), and unitePages().
useStripOptimization()
bool VLayoutGenerator::useStripOptimization () const
useStripOptimization gets whether to use strip optimization.
This method gets whether to use strip optimization when uniting pages.
Returns
m_useStripOptimization
true if optimization should be used when uniting pages.
false if otherwise.
Definition at line 337 of file vlayoutgenerator.cpp.
References m_useStripOptimization.
Member Data Documentation
m_autoCrop
bool VLayoutGenerator::m_autoCrop private
Definition at line 153 of file vlayoutgenerator.h.
Referenced by GetAutoCrop(), GetPapersItems(), SetAutoCrop(), and unitePages().
m_bank
VBank* VLayoutGenerator::m_bank private
Definition at line 143 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), PieceCount(), setCaseType(), setLayoutGap(), setPieces(), unitePages(), and ~VLayoutGenerator().
m_margins
QMarginsF VLayoutGenerator::m_margins private
Definition at line 146 of file vlayoutgenerator.h.
Referenced by GetPrinterFields(), pageHeight(), pageWidth(), and SetPrinterFields().
m_multiplier
quint8 VLayoutGenerator::m_multiplier private
Definition at line 157 of file vlayoutgenerator.h.
Referenced by Generate(), GetMultiplier(), and SetMultiplier().
m_paperHeight
qreal VLayoutGenerator::m_paperHeight private
Definition at line 144 of file vlayoutgenerator.h.
Referenced by gatherPages(), GetPaperHeight(), pageHeight(), and SetPaperHeight().
m_papers
QVector<VLayoutPaper> VLayoutGenerator::m_papers private
Definition at line 142 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), getAllPieceItems(), getAllPieces(), GetPapersItems(), unitePages(), and unitePieces().
m_paperWidth
qreal VLayoutGenerator::m_paperWidth private
Definition at line 145 of file vlayoutgenerator.h.
Referenced by GetPaperWidth(), pageWidth(), and SetPaperWidth().
m_rotate
bool VLayoutGenerator::m_rotate private
Definition at line 151 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), GetRotate(), SetRotate(), and unitePages().
m_rotationIncrement
int VLayoutGenerator::m_rotationIncrement private
Definition at line 152 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), GetRotationIncrease(), SetRotationIncrease(), and unitePages().
m_saveLength
bool VLayoutGenerator::m_saveLength private
Definition at line 154 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), IsSaveLength(), SetSaveLength(), and unitePages().
m_shift
quint32 VLayoutGenerator::m_shift private
Definition at line 150 of file vlayoutgenerator.h.
Referenced by gatherPages(), Generate(), GetShift(), SetShift(), and unitePages().
m_state
LayoutErrors VLayoutGenerator::m_state private
Definition at line 149 of file vlayoutgenerator.h.
Referenced by Abort(), Generate(), and State().
m_stopGeneration
std::atomic_bool VLayoutGenerator::m_stopGeneration private
Definition at line 148 of file vlayoutgenerator.h.
Referenced by Abort(), and Generate().
m_stripOptimized
bool VLayoutGenerator::m_stripOptimized private
Definition at line 156 of file vlayoutgenerator.h.
Referenced by Generate().
m_textAsPaths
bool VLayoutGenerator::m_textAsPaths private
Definition at line 159 of file vlayoutgenerator.h.
Referenced by isTextAsPaths(), and setTextAsPaths().
m_unitePages
bool VLayoutGenerator::m_unitePages private
Definition at line 155 of file vlayoutgenerator.h.
Referenced by IsUnitePages(), and SetUnitePages().
m_usePrinterFields
bool VLayoutGenerator::m_usePrinterFields private
Definition at line 147 of file vlayoutgenerator.h.
Referenced by IsUsePrinterFields(), and SetPrinterFields().
m_useStripOptimization
bool VLayoutGenerator::m_useStripOptimization private
Definition at line 158 of file vlayoutgenerator.h.
Referenced by Generate(), setStripOptimization(), and useStripOptimization().
The documentation for this class was generated from the following files:
src/libs/vlayout/vlayoutgenerator.h
src/libs/vlayout/vlayoutgenerator.cpp