Seamly2D: VGrainlineData Class Reference
VGrainlineData Class Reference
The VGrainlineData class holds information about a grainline like position, size, rotation and visibility.
#include <vgrainlinedata.h>
Public Member Functions
VGrainlineData ()
VGrainlineData (const VGrainlineData &data)
virtual ~VGrainlineData ()
VGrainlineData & operator= (const VGrainlineData &data)
void Swap (VGrainlineData &data) Q_DECL_NOTHROW
QString getLength () const
void setLength (const QString &length)
QString getRotation () const
void setRotation (const QString &rotation)
ArrowType getArrowType () const
void setArrowType (ArrowType type)
quint32 centerAnchorPoint () const
void setCenterAnchorPoint (quint32 centerAnchor)
quint32 topAnchorPoint () const
void setTopAnchorPoint (quint32 topAnchorPoint)
quint32 bottomAnchorPoint () const
void setBottomAnchorPoint (quint32 bottomAnchorPoint)
Public Member Functions inherited from VAbstractFloatItemData
VAbstractFloatItemData ()
VAbstractFloatItemData (const VAbstractFloatItemData &data)
virtual ~VAbstractFloatItemData ()
VAbstractFloatItemData & operator= (const VAbstractFloatItemData &data)
void Swap (VAbstractFloatItemData &data) Q_DECL_NOTHROW
QPointF GetPos () const
void SetPos (const QPointF &ptPos)
bool IsVisible () const
void SetVisible (bool bVisible)
Private Attributes
QSharedDataPointer< VGrainlineDataPrivate > d
Detailed Description
The VGrainlineData class holds information about a grainline like position, size, rotation and visibility.
Definition at line 66 of file vgrainlinedata.h.
Constructor & Destructor Documentation
VGrainlineData() [1/2]
VGrainlineData::VGrainlineData ()
Definition at line 64 of file vgrainlinedata.cpp.
VGrainlineData() [2/2]
VGrainlineData::VGrainlineData (const VGrainlineData & data)
Definition at line 70 of file vgrainlinedata.cpp.
~VGrainlineData()
VGrainlineData::~VGrainlineData () virtual
Definition at line 88 of file vgrainlinedata.cpp.
Member Function Documentation
bottomAnchorPoint()
quint32 VGrainlineData::bottomAnchorPoint () const
Definition at line 152 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), setBottomAnchorPoint(), and PatternPieceDialog::SetPiece().
centerAnchorPoint()
quint32 VGrainlineData::centerAnchorPoint () const
Definition at line 128 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
getArrowType()
ArrowType VGrainlineData::getArrowType () const
Definition at line 116 of file vgrainlinedata.cpp.
References d.
Referenced by VLayoutPiece::setGrainline(), and PatternPieceDialog::SetPiece().
getLength()
QString VGrainlineData::getLength () const
Definition at line 92 of file vgrainlinedata.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
getRotation()
QString VGrainlineData::getRotation () const
Definition at line 104 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
operator=()
VGrainlineData & VGrainlineData::operator= (const VGrainlineData & data)
Definition at line 76 of file vgrainlinedata.cpp.
References d, and VAbstractFloatItemData::operator=().
setArrowType()
void VGrainlineData::setArrowType (ArrowType type)
Definition at line 122 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
setBottomAnchorPoint()
void VGrainlineData::setBottomAnchorPoint (quint32 bottomAnchorPoint)
Definition at line 158 of file vgrainlinedata.cpp.
References bottomAnchorPoint(), and d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
setCenterAnchorPoint()
void VGrainlineData::setCenterAnchorPoint (quint32 centerAnchor)
Definition at line 134 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
setLength()
void VGrainlineData::setLength (const QString & length)
Definition at line 98 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceGrainline(), and PatternPieceTool::SaveResizeGrainline().
setRotation()
void VGrainlineData::setRotation (const QString & rotation)
Definition at line 110 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceGrainline(), and PatternPieceTool::SaveRotateGrainline().
setTopAnchorPoint()
void VGrainlineData::setTopAnchorPoint (quint32 topAnchorPoint)
Definition at line 146 of file vgrainlinedata.cpp.
References d, and topAnchorPoint().
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
Swap()
void VGrainlineData::Swap (VGrainlineData & data)
Definition at line 60 of file vgrainlinedata.cpp.
References VAbstractFloatItemData::Swap().
topAnchorPoint()
quint32 VGrainlineData::topAnchorPoint () const
Definition at line 140 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), PatternPieceDialog::SetPiece(), and setTopAnchorPoint().
Member Data Documentation
d
QSharedDataPointer<VGrainlineDataPrivate> VGrainlineData::d private
Definition at line 101 of file vgrainlinedata.h.
Referenced by bottomAnchorPoint(), centerAnchorPoint(), getArrowType(), getLength(), getRotation(), operator=(), setArrowType(), setBottomAnchorPoint(), setCenterAnchorPoint(), setLength(), setRotation(), setTopAnchorPoint(), and topAnchorPoint().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/floatItemData/vgrainlinedata.h
src/libs/vpatterndb/floatItemData/vgrainlinedata.cpp