Seamly2D: VPosition Class Reference
VPosition Class Reference
#include <vposition.h>
Public Member Functions
VPosition (const VContour &sheet, int sheetEdgeNum, const VLayoutPiece &piece, int pieceEdgeNum, std::atomic_bool *stop, bool rotate, int rotationIncrement, bool saveLength)
VPosition constructor.
virtual ~VPosition () Q_DECL_OVERRIDE
virtual void run () Q_DECL_OVERRIDE
run run the thread to position piece.
VBestSquare getBestResult () const
getBestResult getter for m_bestResult.
Private Types
enum class IntersectionType : char { NoIntersection = 0 , Intersection = 1 }
keep angle between global edge and piece edge. Need for optimizing rotation.
Private Member Functions
void saveCandidate (VBestSquare &bestResult, const VLayoutPiece &piece, int pieceEdgeNum, int sheetEdgeNum, BestFrom type)
saveCandidate saves the best square.
bool edgesIntersect (VLayoutPiece &piece, int &pieceEdgeNum, int sheetEdgeNum)
edgesIntersect check for intersection between piece and sheet
bool rotatedEdgeIntersects (VLayoutPiece &piece, int pieceEdgeNum, int sheetEdgeNum, int angle) const
rotatedEdgeIntersects check for intersection between rotated piece and sheet
IntersectionType intersectionType (const VLayoutPiece &piece) const
intersectionType get the intersection type between sheet and piece.
bool sheetContains (const QRectF &rect) const
sheetContains check if sheet contains piece.
void combineEdges (VLayoutPiece &piece, const int &pieceEdgeNum, const QLineF &sheetEdge)
combineEdges rotate and move piece to contour edge.
void rotateEdges (VLayoutPiece &piece, int pieceEdgeNum, const QLineF &sheetEdge, int angle) const
rotateEdges rotate and move piece to sheet edge.
void rotate (int increment)
rotate rotate the pattern piece.
Private Attributes
VBestSquare m_bestResult
const VContour m_sheet
int m_sheetEdgeNum
const VLayoutPiece m_piece
int m_pieceEdgeNum
std::atomic_bool * m_stop
bool m_rotate
int m_rotationIncrement
qreal m_angleBetween
Detailed Description
Definition at line 66 of file vposition.h.
Member Enumeration Documentation
IntersectionType
enum class VPosition::IntersectionType : char strong private
keep angle between global edge and piece edge. Need for optimizing rotation.
Enumerator
NoIntersection
Intersection
Definition at line 88 of file vposition.h.
Constructor & Destructor Documentation
VPosition()
VPosition::VPosition (const VContour & sheet, int sheetEdgeNum, const VLayoutPiece & piece, int pieceEdgeNum, std::atomic_bool * stop, bool rotate, int rotationIncrement, bool saveLength)
VPosition constructor.
This consrtucts an instance of VPosition.
Parameters
sheet
sheetEdgeNum
piece
pieceEdgeNum
stop
rotate
rotationIncrement
saveLength
Definition at line 83 of file vposition.cpp.
References m_rotationIncrement.
~VPosition()
virtual VPosition::~VPosition () inline virtual
Definition at line 71 of file vposition.h.
Member Function Documentation
combineEdges()
void VPosition::combineEdges (VLayoutPiece & piece, const int & pieceEdgeNum, const QLineF & sheetEdge) private
combineEdges rotate and move piece to contour edge.
This method rotates and moves piece near to the sheet edge.
Parameters
piece layout piece.
pieceEdgeNum piece edge number.
sheetEdge line that represents the sheet edge.
Returns
void.
Definition at line 347 of file vposition.cpp.
References VContour::GetContour(), VLayoutPiece::LayoutEdge(), m_angleBetween, m_sheet, VLayoutPiece::pieceEdge(), VLayoutPiece::Rotate(), and VLayoutPiece::Translate().
Referenced by edgesIntersect().
edgesIntersect()
bool VPosition::edgesIntersect (VLayoutPiece & piece, int & pieceEdgeNum, int sheetEdgeNum) private
edgesIntersect check for intersection between piece and sheet
This method checks if the pattern piece edge intersects with the sheet edge.
Parameters
piece pattern piece being added to sheet.
pieceEdgeNum edge number of piece to be combined with the sheet edge.
sheetEdgeNum edge of sheet piece is being comibed with.
Returns
bool.
true if there no intersection.
false if it has an intersection.
Definition at line 181 of file vposition.cpp.
References combineEdges(), VContour::GetContour(), VContour::GlobalEdge(), Intersection, intersectionType(), VAbstractPiece::IsForbidFlipping(), VLayoutPiece::LayoutEdgeByPoint(), m_sheet, VLayoutPiece::Mirror(), NoIntersection, VLayoutPiece::pieceBoundingRect(), VLayoutPiece::pieceEdgeByPoint(), and sheetContains().
Referenced by run().
getBestResult()
VBestSquare VPosition::getBestResult () const
getBestResult getter for m_bestResult.
This method gets and returns m_bestResult.
Returns
VBestSquare m_bestResult.
Definition at line 143 of file vposition.cpp.
References m_bestResult.
intersectionType()
VPosition::IntersectionType VPosition::intersectionType (const VLayoutPiece & piece) const private
intersectionType get the intersection type between sheet and piece.
This method checks if the bounding box of a piece intersects with sheet bounding box.
Parameters
piece layput piece.
Returns
IntersectionType intersection type
NoIntersection = 0,
Intersection = 1,
Definition at line 301 of file vposition.cpp.
References VContour::BoundingRect(), VContour::ContourPath(), VLayoutPiece::createMainPath(), Intersection, VLayoutPiece::LayoutAllowancePath(), VLayoutPiece::LayoutBoundingRect(), m_sheet, NoIntersection, and VLayoutPiece::pieceBoundingRect().
Referenced by edgesIntersect(), and rotatedEdgeIntersects().
rotate()
void VPosition::rotate (int increment) private
rotate rotate the pattern piece.
This method rotates the pattern piece by the number of degrees in incrmentuntil it intersects with the sheet. The best square result is saved.
Parameters
increment pattern piece rotation angle.
Returns
void.
Definition at line 416 of file vposition.cpp.
References m_angleBetween, m_bestResult, m_piece, m_pieceEdgeNum, m_sheetEdgeNum, m_stop, rotatedEdgeIntersects(), Rotation, saveCandidate(), and VFuzzyComparePossibleNulls().
Referenced by run().
rotatedEdgeIntersects()
bool VPosition::rotatedEdgeIntersects (VLayoutPiece & piece, int pieceEdgeNum, int sheetEdgeNum, int angle) const private
rotatedEdgeIntersects check for intersection between rotated piece and sheet
This method checks if rotated pattern piece edge intersects with the sheet edge.
Parameters
piece pattern piece being added to sheet.
pieceEdgeNum edge number of piece to be combined with the sheet edge.
sheetEdgeNum edge of sheet piece is being comibed with.
Returns
bool.
true if there no intersection.
false if it has an intersection.
Definition at line 264 of file vposition.cpp.
References VContour::GlobalEdge(), Intersection, intersectionType(), m_sheet, NoIntersection, VLayoutPiece::pieceBoundingRect(), rotateEdges(), and sheetContains().
Referenced by rotate().
rotateEdges()
void VPosition::rotateEdges (VLayoutPiece & piece, int pieceEdgeNum, const QLineF & sheetEdge, int angle) const private
rotateEdges rotate and move piece to sheet edge.
This method rotates and moves piece near to the sheet edge.
Parameters
piece layout piece.
sheetEdge line that represents the sheet edge.
pieceEdgeNum piece edge number.
angle piece rotation angle.
Returns
void.
Definition at line 386 of file vposition.cpp.
References VContour::GetContour(), VLayoutPiece::LayoutEdge(), m_sheet, VLayoutPiece::pieceEdge(), VLayoutPiece::Rotate(), and VLayoutPiece::Translate().
Referenced by rotatedEdgeIntersects().
run()
void VPosition::run () virtual
run run the thread to position piece.
This method runs the thread that positions the piece near to the sheet edge.
Definition at line 107 of file vposition.cpp.
References Combine, edgesIntersect(), VContour::GetContour(), m_bestResult, m_piece, m_pieceEdgeNum, m_rotate, m_rotationIncrement, m_sheet, m_sheetEdgeNum, m_stop, rotate(), and saveCandidate().
saveCandidate()
void VPosition::saveCandidate (VBestSquare & bestResult, const VLayoutPiece & piece, int pieceEdgeNum, int sheetEdgeNum, BestFrom type) private
saveCandidate saves the best square.
This method saves the resulting new size after adding the piece to the sheet.
Parameters
bestResult new sheet size saved here.
piece pattern piece being added to sheet.
pieceEdgeNum edge number of piece to be combined with the sheet edge.
sheetEdgeNum edge of sheet piece is being comibed with.
type type of best sqaure being saved.
Returns
void.
Definition at line 160 of file vposition.cpp.
References VLayoutPiece::getTransform(), VLayoutPiece::isMirror(), m_sheet, VBestSquare::NewResult(), and VContour::UniteWithContour().
Referenced by rotate(), and run().
sheetContains()
bool VPosition::sheetContains (const QRectF & rect) const private
sheetContains check if sheet contains piece.
This method checks if the bounding box of a piece is contained in the sheet bounding box.
Parameters
rect bounding rectangle of the piece.
Returns
bool
true if sheet contains piece.
false if sheet does not contain piece.
Definition at line 331 of file vposition.cpp.
References VContour::GetHeight(), VContour::GetWidth(), and m_sheet.
Referenced by edgesIntersect(), and rotatedEdgeIntersects().
Member Data Documentation
m_angleBetween
qreal VPosition::m_angleBetween private
Definition at line 86 of file vposition.h.
Referenced by combineEdges(), and rotate().
m_bestResult
VBestSquare VPosition::m_bestResult private
Definition at line 78 of file vposition.h.
Referenced by getBestResult(), rotate(), and run().
m_piece
const VLayoutPiece VPosition::m_piece private
Definition at line 81 of file vposition.h.
Referenced by rotate(), and run().
m_pieceEdgeNum
int VPosition::m_pieceEdgeNum private
Definition at line 82 of file vposition.h.
Referenced by rotate(), and run().
m_rotate
bool VPosition::m_rotate private
Definition at line 84 of file vposition.h.
Referenced by run().
m_rotationIncrement
int VPosition::m_rotationIncrement private
Definition at line 85 of file vposition.h.
Referenced by run(), and VPosition().
m_sheet
const VContour VPosition::m_sheet private
Definition at line 79 of file vposition.h.
Referenced by combineEdges(), edgesIntersect(), intersectionType(), rotatedEdgeIntersects(), rotateEdges(), run(), saveCandidate(), and sheetContains().
m_sheetEdgeNum
int VPosition::m_sheetEdgeNum private
Definition at line 80 of file vposition.h.
Referenced by rotate(), and run().
m_stop
std::atomic_bool* VPosition::m_stop private
Definition at line 83 of file vposition.h.
Referenced by rotate(), and run().
The documentation for this class was generated from the following files:
src/libs/vlayout/vposition.h
src/libs/vlayout/vposition.cpp